spring.application.name=EDCustom

spring.datasource.url=jdbc:postgresql://svc.sel5.cloudtype.app:31617/
spring.datasource.username=root
spring.datasource.password=3321
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.driver-class-name=org.postgresql.Driver


springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
springdoc.api-docs.path=/docs..
springdoc.swagger-ui.path=/docs


springdoc.default-consumes-media-type=application/json;charset=UTF-8
springdoc.default-produces-media-type=application/json;charset=UTF-8

kakao.client-id=9b8440c52cc5a7dd32647c76aade83d3
kakao.client-secret=AUVMbRDCPyoHrgKM2LFxghTUgh0FP634
kakao.redirect-uri=http://localhost:5173/KakaoRedirect
kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
kakao.token-uri=https://kauth.kakao.com/oauth/token
kakao.user-info-uri=https://kapi.kakao.com/v2/user/me

spring.ai.openai.api-key=sk-proj-OEj05MikEkzmQZ8liVN8T3BlbkFJSFt10j9XVLv2DvRQa2VX

app.firebase-configuration-file=./serviceAccountKey.json
app.firebase-bucket=cuskey-44d99.firebasestorage.app
app.firebase-profile=cuskey-44d99.firebasestorage.app/profile